trigger:
  - master
  - development

variables:
  - group: web-ui
  - name: isDevelopmentOrMasterBranch
    value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/development'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))]

resources:
  repositories:
    - repository: templates
      type: git
      name: development/azure-templates
      ref: v2

stages:
  - template: next.yml@templates
