nodeLinker: node-modules

npmScopes:
  codana:
    npmAlwaysAuth: true
    npmRegistryServer: "https://pkgs.dev.azure.com/softwarebw2021/_packaging/softwarebw/npm/registry"
  econsor-mobile:
    npmAlwaysAuth: true
    npmRegistryServer: "https://pkgs.dev.azure.com/softwarebw2021/_packaging/softwarebw/npm/registry"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
